spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/album-discovery-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 753258
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org:
      springframework:
        transaction: DEBUG

